import { ChangeDetectionStrategy, Component, input, model } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { FaIconComponent } from '@fortawesome/angular-fontawesome';
import { FilterPipe } from '../../pipe/filter.pipe';
import { GroupByPipe } from '../../pipe/group-by.pipe';

@Component({
    selector: 'app-icon-picker',
    changeDetection: ChangeDetectionStrategy.OnPush,
    templateUrl: './icon-picker.component.html',
    styleUrls: ['./icon-picker.component.scss'],
    imports: [FaIconComponent, FormsModule, FilterPipe, GroupByPipe]
})
export class IconPickerComponent {

  icon: string = "";
  searchText: string = "";

  iconList = [
    // --- NAVIGATION & ARROWS ---
    { key: "fas:bars", value: ["fas", "bars"], category: "Navigation & Arrows" },
    { key: "fas:home", value: ["fas", "home"], category: "Navigation & Arrows" },
    { key: "fas:ellipsis-v", value: ["fas", "ellipsis-v"], category: "Navigation & Arrows" },
    { key: "fas:ellipsis-h", value: ["fas", "ellipsis-h"], category: "Navigation & Arrows" },
    { key: "fas:external-link-alt", value: ["fas", "external-link-alt"], category: "Navigation & Arrows" },
    { key: "fas:arrow-up", value: ["fas", "arrow-up"], category: "Navigation & Arrows" },
    { key: "fas:arrow-down", value: ["fas", "arrow-down"], category: "Navigation & Arrows" },
    { key: "fas:arrow-left", value: ["fas", "arrow-left"], category: "Navigation & Arrows" },
    { key: "fas:arrow-right", value: ["fas", "arrow-right"], category: "Navigation & Arrows" },
    { key: "fas:chevron-left", value: ["fas", "chevron-left"], category: "Navigation & Arrows" },
    { key: "fas:chevron-right", value: ["fas", "chevron-right"], category: "Navigation & Arrows" },
    { key: "fas:angle-up", value: ["fas", "angle-up"], category: "Navigation & Arrows" },
    { key: "fas:angle-down", value: ["fas", "angle-down"], category: "Navigation & Arrows" },
    { key: "fas:angle-left", value: ["fas", "angle-left"], category: "Navigation & Arrows" },
    { key: "fas:angle-right", value: ["fas", "angle-right"], category: "Navigation & Arrows" },
    { key: "fas:angle-double-left", value: ["fas", "angle-double-left"], category: "Navigation & Arrows" },
    { key: "fas:angle-double-right", value: ["fas", "angle-double-right"], category: "Navigation & Arrows" },

    // --- STATUS & ALERTS ---
    { key: "fas:bell", value: ["fas", "bell"], category: "Status & Alerts" },
    { key: "far:bell", value: ["far", "bell"], category: "Status & Alerts" },
    { key: "fas:check", value: ["fas", "check"], category: "Status & Alerts" },
    { key: "fas:check-circle", value: ["fas", "check-circle"], category: "Status & Alerts" },
    { key: "fas:times", value: ["fas", "times"], category: "Status & Alerts" },
    { key: "fas:times-circle", value: ["fas", "times-circle"], category: "Status & Alerts" },
    { key: "fas:exclamation-triangle", value: ["fas", "exclamation-triangle"], category: "Status & Alerts" },
    { key: "fas:exclamation-circle", value: ["fas", "exclamation-circle"], category: "Status & Alerts" },
    { key: "fas:info-circle", value: ["fas", "info-circle"], category: "Status & Alerts" },
    { key: "fas:question", value: ["fas", "question"], category: "Status & Alerts" },
    { key: "far:question-circle", value: ["far", "question-circle"], category: "Status & Alerts" },
    { key: "fas:spinner", value: ["fas", "spinner"], category: "Status & Alerts" },
    { key: "fas:circle-notch", value: ["fas", "circle-notch"], category: "Status & Alerts" },
    { key: "fas:ban", value: ["fas", "ban"], category: "Status & Alerts" },
    { key: "fas:shield-alt", value: ["fas", "shield-alt"], category: "Status & Alerts" },
    { key: "fas:lock", value: ["fas", "lock"], category: "Status & Alerts" },
    { key: "fas:unlock", value: ["fas", "unlock"], category: "Status & Alerts" },

    // --- USERS & IDENTITY ---
    { key: "far:user", value: ["far", "user"], category: "Users & Identity" },
    { key: "far:circle-user", value: ["far", "circle-user"], category: "Users & Identity" },
    { key: "fas:users", value: ["fas", "users"], category: "Users & Identity" },
    { key: "fas:user-plus", value: ["fas", "user-plus"], category: "Users & Identity" },
    { key: "fas:user-edit", value: ["fas", "user-edit"], category: "Users & Identity" },
    { key: "fas:user-shield", value: ["fas", "user-shield"], category: "Users & Identity" },
    { key: "fas:users-cog", value: ["fas", "users-cog"], category: "Users & Identity" },
    { key: "fas:chalkboard-teacher", value: ["fas", "chalkboard-teacher"], category: "Users & Identity" },
    { key: "fas:id-card", value: ["fas", "id-card"], category: "Users & Identity" },
    { key: "far:id-card", value: ["far", "id-card"], category: "Users & Identity" },
    { key: "fas:address-book", value: ["fas", "address-book"], category: "Users & Identity" },

    // --- FILES & FOLDERS ---
    { key: "fas:file", value: ["fas", "file"], category: "Files & Folders" },
    { key: "far:file", value: ["far", "file"], category: "Files & Folders" },
    { key: "far:file-lines", value: ["far", "file-lines"], category: "Files & Folders" },
    { key: "far:file-code", value: ["far", "file-code"], category: "Files & Folders" },
    { key: "fas:file-pdf", value: ["fas", "file-pdf"], category: "Files & Folders" },
    { key: "fas:file-excel", value: ["fas", "file-excel"], category: "Files & Folders" },
    { key: "fas:file-csv", value: ["fas", "file-csv"], category: "Files & Folders" },
    { key: "fas:file-waveform", value: ["fas", "file-waveform"], category: "Files & Folders" },
    { key: "far:file-archive", value: ["far", "file-archive"], category: "Files & Folders" },
    { key: "fas:folder", value: ["fas", "folder"], category: "Files & Folders" },
    { key: "far:folder", value: ["far", "folder"], category: "Files & Folders" },
    { key: "fas:scroll", value: ["fas", "scroll"], category: "Files & Folders" },
    { key: "fas:upload", value: ["fas", "upload"], category: "Files & Folders" },
    { key: "fas:download", value: ["fas", "download"], category: "Files & Folders" },
    { key: "fas:cloud-upload-alt", value: ["fas", "cloud-upload-alt"], category: "Files & Folders" },
    { key: "fas:cloud-download-alt", value: ["fas", "cloud-download-alt"], category: "Files & Folders" },
    { key: "fas:file-import", value: ["fas", "file-import"], category: "Files & Folders" },
    { key: "fas:file-export", value: ["fas", "file-export"], category: "Files & Folders" },
    { key: "fas:save", value: ["fas", "save"], category: "Files & Folders" },
    { key: "fas:copy", value: ["fas", "copy"], category: "Files & Folders" },
    { key: "fas:print", value: ["fas", "print"], category: "Files & Folders" },
    { key: "fas:paperclip", value: ["fas", "paperclip"], category: "Files & Folders" },

    // --- DATA & TECH ---
    { key: "fas:chart-bar", value: ["fas", "chart-bar"], category: "Data & Tech" },
    { key: "fas:chart-pie", value: ["fas", "chart-pie"], category: "Data & Tech" },
    { key: "fas:chart-line", value: ["fas", "chart-line"], category: "Data & Tech" },
    { key: "fas:chart-area", value: ["fas", "chart-area"], category: "Data & Tech" },
    { key: "fas:table", value: ["fas", "table"], category: "Data & Tech" },
    { key: "fas:database", value: ["fas", "database"], category: "Data & Tech" },
    { key: "fas:server", value: ["fas", "server"], category: "Data & Tech" },
    { key: "fas:cloud", value: ["fas", "cloud"], category: "Data & Tech" },
    { key: "fas:code", value: ["fas", "code"], category: "Data & Tech" },
    { key: "fas:code-branch", value: ["fas", "code-branch"], category: "Data & Tech" },
    { key: "fas:terminal", value: ["fas", "terminal"], category: "Data & Tech" },
    { key: "fas:sitemap", value: ["fas", "sitemap"], category: "Data & Tech" },
    { key: "fas:diagram-project", value: ["fas", "diagram-project"], category: "Data & Tech" },
    { key: "fas:circle-nodes", value: ["fas", "circle-nodes"], category: "Data & Tech" },
    { key: "fas:hexagon-nodes", value: ["fas", "hexagon-nodes"], category: "Data & Tech" },
    { key: "fas:qrcode", value: ["fas", "qrcode"], category: "Data & Tech" },
    { key: "fas:laptop-file", value: ["fas", "laptop-file"], category: "Data & Tech" },
    { key: "fas:wifi", value: ["fas", "wifi"], category: "Data & Tech" },
    { key: "fas:brain", value: ["fas", "brain"], category: "Data & Tech" },
    { key: "fas:signal", value: ["fas", "signal"], category: "Data & Tech" },

    // --- ACTIONS & EDITING ---
    { key: "fas:plus", value: ["fas", "plus"], category: "Actions & Editing" },
    { key: "fas:minus", value: ["fas", "minus"], category: "Actions & Editing" },
    { key: "fas:edit", value: ["fas", "edit"], category: "Actions & Editing" },
    { key: "fas:pencil-alt", value: ["fas", "pencil-alt"], category: "Actions & Editing" },
    { key: "fas:pen", value: ["fas", "pen"], category: "Actions & Editing" },
    { key: "fas:trash", value: ["fas", "trash"], category: "Actions & Editing" },
    { key: "fas:align-left", value: ["fas", "align-left"], category: "Actions & Editing" },
    { key: "fas:align-center", value: ["fas", "align-center"], category: "Actions & Editing" },
    { key: "fas:align-right", value: ["fas", "align-right"], category: "Actions & Editing" },
    { key: "fas:align-justify", value: ["fas", "align-justify"], category: "Actions & Editing" },
    { key: "fas:reply", value: ["fas", "reply"], category: "Actions & Editing" },
    { key: "fas:share", value: ["fas", "share"], category: "Actions & Editing" },
    { key: "fas:share-alt", value: ["fas", "share-alt"], category: "Actions & Editing" },
    { key: "fas:undo", value: ["fas", "undo"], category: "Actions & Editing" },
    { key: "fas:redo", value: ["fas", "redo"], category: "Actions & Editing" },
    { key: "fas:sync", value: ["fas", "sync"], category: "Actions & Editing" },
    { key: "fas:search", value: ["fas", "search"], category: "Actions & Editing" },
    { key: "fas:filter", value: ["fas", "filter"], category: "Actions & Editing" },
    { key: "fas:expand", value: ["fas", "expand"], category: "Actions & Editing" },
    { key: "fas:compress", value: ["fas", "compress"], category: "Actions & Editing" },
    { key: "fas:stop", value: ["fas", "stop"], category: "Actions & Editing" },
    { key: "fas:window-restore", value: ["fas", "window-restore"], category: "Actions & Editing" },
    { key: "fas:sign-out-alt", value: ["fas", "sign-out-alt"], category: "Actions & Editing" },
    { key: "fas:sign-in-alt", value: ["fas", "sign-in-alt"], category: "Actions & Editing" },

    // --- UI ELEMENTS ---
    { key: "fas:check-square", value: ["fas", "check-square"], category: "UI Elements" },
    { key: "far:check-square", value: ["far", "check-square"], category: "UI Elements" },
    { key: "fas:square", value: ["fas", "square"], category: "UI Elements" },
    { key: "far:square", value: ["far", "square"], category: "UI Elements" },
    { key: "fas:circle", value: ["fas", "circle"], category: "UI Elements" },
    { key: "far:circle", value: ["far", "circle"], category: "UI Elements" },
    { key: "fas:plus-circle", value: ["fas", "plus-circle"], category: "UI Elements" },
    { key: "fas:plus-square", value: ["fas", "plus-square"], category: "UI Elements" },
    { key: "far:plus-square", value: ["far", "plus-square"], category: "UI Elements" },
    { key: "fas:minus-square", value: ["fas", "minus-square"], category: "UI Elements" },
    { key: "far:minus-square", value: ["far", "minus-square"], category: "UI Elements" },
    { key: "far:caret-square-down", value: ["far", "caret-square-down"], category: "UI Elements" },
    { key: "fas:grip-vertical", value: ["fas", "grip-vertical"], category: "UI Elements" },
    { key: "fas:toggle-on", value: ["fas", "toggle-on"], category: "UI Elements" },
    { key: "fas:toggle-off", value: ["fas", "toggle-off"], category: "UI Elements" },
    { key: "fas:list", value: ["fas", "list"], category: "UI Elements" },
    { key: "fas:list-alt", value: ["fas", "list-alt"], category: "UI Elements" },
    { key: "fas:list-ol", value: ["fas", "list-ol"], category: "UI Elements" },
    { key: "fas:stream", value: ["fas", "stream"], category: "UI Elements" },
    { key: "fas:th", value: ["fas", "th"], category: "UI Elements" },
    { key: "fas:th-large", value: ["fas", "th-large"], category: "UI Elements" },
    { key: "fas:sliders", value: ["fas", "sliders"], category: "UI Elements" },
    { key: "fas:sort", value: ["fas", "sort"], category: "UI Elements" },
    { key: "fas:asterisk", value: ["fas", "asterisk"], category: "UI Elements" },

    // --- E-COMMERCE & BILLING ---
    { key: "fas:shopping-cart", value: ["fas", "shopping-cart"], category: "E-Commerce & Billing" },
    { key: "fas:shopping-bag", value: ["fas", "shopping-bag"], category: "E-Commerce & Billing" },
    { key: "fas:briefcase", value: ["fas", "briefcase"], category: "E-Commerce & Billing" },
    { key: "fas:credit-card", value: ["fas", "credit-card"], category: "E-Commerce & Billing" },
    { key: "far:credit-card", value: ["far", "credit-card"], category: "E-Commerce & Billing" },
    { key: "fas:money-bill-wave", value: ["fas", "money-bill-wave"], category: "E-Commerce & Billing" },
    { key: "fas:coins", value: ["fas", "coins"], category: "E-Commerce & Billing" },
    { key: "fas:hand-holding-usd", value: ["fas", "hand-holding-usd"], category: "E-Commerce & Billing" },
    { key: "fas:receipt", value: ["fas", "receipt"], category: "E-Commerce & Billing" },
    { key: "fas:file-invoice-dollar", value: ["fas", "file-invoice-dollar"], category: "E-Commerce & Billing" },
    { key: "fas:tag", value: ["fas", "tag"], category: "E-Commerce & Billing" },
    { key: "fas:tags", value: ["fas", "tags"], category: "E-Commerce & Billing" },
    { key: "fas:box", value: ["fas", "box"], category: "E-Commerce & Billing" },

    // --- INTERACTION & COMMUNICATION ---
    { key: "fas:star", value: ["fas", "star"], category: "Interaction & Comm" },
    { key: "far:star", value: ["far", "star"], category: "Interaction & Comm" },
    { key: "fas:heart", value: ["fas", "heart"], category: "Interaction & Comm" },
    { key: "far:heart", value: ["far", "heart"], category: "Interaction & Comm" },
    { key: "fas:bookmark", value: ["fas", "bookmark"], category: "Interaction & Comm" },
    { key: "far:bookmark", value: ["far", "bookmark"], category: "Interaction & Comm" },
    { key: "far:thumbs-up", value: ["far", "thumbs-up"], category: "Interaction & Comm" },
    { key: "far:envelope", value: ["far", "envelope"], category: "Interaction & Comm" },
    { key: "fas:inbox", value: ["fas", "inbox"], category: "Interaction & Comm" },
    { key: "fas:paper-plane", value: ["fas", "paper-plane"], category: "Interaction & Comm" },
    { key: "fas:mail-bulk", value: ["fas", "mail-bulk"], category: "Interaction & Comm" },
    { key: "far:comment-dots", value: ["far", "comment-dots"], category: "Interaction & Comm" },
    { key: "far:message", value: ["far", "message"], category: "Interaction & Comm" },
    { key: "fas:phone", value: ["fas", "phone"], category: "Interaction & Comm" },
    { key: "fas:fax", value: ["fas", "fax"], category: "Interaction & Comm" },
    { key: "fas:headset", value: ["fas", "headset"], category: "Interaction & Comm" },
    { key: "fas:bullhorn", value: ["fas", "bullhorn"], category: "Interaction & Comm" },

    // --- OBJECTS & MISC ---
    { key: "fas:building", value: ["fas", "building"], category: "Objects & Misc" },
    { key: "fas:calendar", value: ["fas", "calendar"], category: "Objects & Misc" },
    { key: "far:calendar-alt", value: ["far", "calendar-alt"], category: "Objects & Misc" },
    { key: "far:clock", value: ["far", "clock"], category: "Objects & Misc" },
    { key: "fas:globe", value: ["fas", "globe"], category: "Objects & Misc" },
    { key: "fas:map-marked-alt", value: ["fas", "map-marked-alt"], category: "Objects & Misc" },
    { key: "fas:location-dot", value: ["fas", "location-dot"], category: "Objects & Misc" },
    { key: "fas:location-crosshairs", value: ["fas", "location-crosshairs"], category: "Objects & Misc" },
    { key: "fas:magnifying-glass-location", value: ["fas", "magnifying-glass-location"], category: "Objects & Misc" },
    { key: "fas:plane", value: ["fas", "plane"], category: "Objects & Misc" },
    { key: "fas:rocket", value: ["fas", "rocket"], category: "Objects & Misc" },
    { key: "fas:laptop-medical", value: ["fas", "laptop-medical"], category: "Objects & Misc" },
    { key: "fas:mobile-alt", value: ["fas", "mobile-alt"], category: "Objects & Misc" },
    { key: "fas:image", value: ["fas", "image"], category: "Objects & Misc" },
    { key: "fas:photo-film", value: ["fas", "photo-film"], category: "Objects & Misc" },
    { key: "fas:microphone", value: ["fas", "microphone"], category: "Objects & Misc" },
    { key: "fas:bolt", value: ["fas", "bolt"], category: "Objects & Misc" },
    { key: "fas:robot", value: ["fas", "robot"], category: "Objects & Misc" },
    { key: "fas:cog", value: ["fas", "cog"], category: "Objects & Misc" },
    { key: "fas:tachometer-alt", value: ["fas", "tachometer-alt"], category: "Objects & Misc" },
    { key: "fas:university", value: ["fas", "university"], category: "Objects & Misc" },
    { key: "fas:flag", value: ["fas", "flag"], category: "Objects & Misc" },
    { key: "far:flag", value: ["far", "flag"], category: "Objects & Misc" },
    { key: "fas:history", value: ["fas", "history"], category: "Objects & Misc" },
    { key: "fas:tasks", value: ["fas", "tasks"], category: "Objects & Misc" },
    { key: "fas:layer-group", value: ["fas", "layer-group"], category: "Objects & Misc" },
    { key: "fas:signature", value: ["fas", "signature"], category: "Objects & Misc" },
    { key: "fas:hashtag", value: ["fas", "hashtag"], category: "Objects & Misc" },
    { key: "fas:key", value: ["fas", "key"], category: "Objects & Misc" },
    { key: "fas:link", value: ["fas", "link"], category: "Objects & Misc" },
    { key: "fas:random", value: ["fas", "random"], category: "Objects & Misc" },
    { key: "far:eye", value: ["far", "eye"], category: "Objects & Misc" },
    { key: "far:eye-slash", value: ["far", "eye-slash"], category: "Objects & Misc" },
    { key: "fas:play", value: ["fas", "play"], category: "Objects & Misc" },
    { key: "fas:quidditch", value: ["fas", "quidditch"], category: "Objects & Misc" },
    { key: "far:camera", value: ["far", "camera"], category: "Objects & Misc" },
    { key: "fas:utensils", value: ["fas", "utensils"], category: "Objects & Misc" },
    { key: "fas:award", value: ["fas", "award"], category: "Objects & Misc" },
    { key: "fas:bed", value: ["fas", "bed"], category: "Objects & Misc" },
    { key: "fas:book", value: ["fas", "book"], category: "Objects & Misc" },
    { key: "fas:lightbulb", value: ["fas", "lightbulb"], category: "Objects & Misc" },
    { key: "fas:couch", value: ["fas", "couch"], category: "Objects & Misc" },

    // --- BRANDS ---
    { key: "fab:google", value: ["fab", "google"], category: "Brands" },
    { key: "fab:facebook-f", value: ["fab", "facebook-f"], category: "Brands" },
    { key: "fab:github", value: ["fab", "github"], category: "Brands" },
    { key: "fab:linkedin", value: ["fab", "linkedin"], category: "Brands" },
    { key: "fab:microsoft", value: ["fab", "microsoft"], category: "Brands" },
    { key: "fab:twitter", value: ["fab", "twitter"], category: "Brands" },
    { key: "fab:uncharted", value: ["fab", "uncharted"], category: "Brands" },
    { key: "fab:wpforms", value: ["fab", "wpforms"], category: "Brands" },
    { key: "fab:whatsapp", value: ["fab", "whatsapp"], category: "Brands" },
    { key: "fab:instagram", value: ["fab", "instagram"], category: "Brands" },
    { key: "fab:youtube", value: ["fab", "youtube"], category: "Brands" }
  ];

  model = model<string>();

  showNone = input<boolean>();

  public change(model) {
    this.model.set(model);
  }

}