name: Deploy to KBORNEO Server

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'
      - '.gitlab/ci/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (legacy peer deps)
        run: npm ci --legacy-peer-deps

      - name: Use leap angular config
        run: cp angular-kborneo.json angular.json

      - name: Build Angular app
        run: npx ng build --configuration production

      - name: List build output
        run: ls -lah dist/design/browser

      - name: Generate SHA256 checksum file
        run: |
          cd dist/design/browser
          find . -type f -exec sha256sum {} \; > sha256sum.txt

      - name: Clean remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SFTP_HOST_KBORNEO }}
          username: ${{ secrets.SFTP_USER_KBORNEO }}
          password: ${{ secrets.SFTP_PASS_KBORNEO }}
          script: |
            rm -rf /var/www/vhosts/kborneo.my/httpdocs/design/*

      - name: Upload app files and checksum
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST_KBORNEO }}
          username: ${{ secrets.SFTP_USER_KBORNEO }}
          password: ${{ secrets.SFTP_PASS_KBORNEO }}
          source: dist/design/browser/*
          target: /var/www/vhosts/kborneo.my/httpdocs/design/
          strip_components: 3

      - name: Set file permissions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SFTP_HOST_KBORNEO }}
          username: ${{ secrets.SFTP_USER_KBORNEO }}
          password: ${{ secrets.SFTP_PASS_KBORNEO }}
          script: |
            chmod -R 755 /var/www/vhosts/kborneo.my/httpdocs/design
            chown -R kborneo:psacln /var/www/vhosts/kborneo.my/httpdocs/design

      - name: Verify remote file integrity
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SFTP_HOST_KBORNEO }}
          username: ${{ secrets.SFTP_USER_KBORNEO }}
          password: ${{ secrets.SFTP_PASS_KBORNEO }}
          script: |
            cd /var/www/vhosts/kborneo.my/httpdocs/design
            sha256sum -c sha256sum.txt || exit 1

      - name: Print remote index.html hash
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SFTP_HOST_KBORNEO }}
          username: ${{ secrets.SFTP_USER_KBORNEO }}
          password: ${{ secrets.SFTP_PASS_KBORNEO }}
          script: |
            sha256sum /var/www/vhosts/kborneo.my/httpdocs/design/index.html || echo "index.html not found"
