name: Deploy to LEAP Server

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (legacy peer deps)
        run: npm ci --legacy-peer-deps

      - name: Use leap angular config
        run: cp angular-leap.json angular.json

      - name: Build Angular app
        run: npx ng build --configuration production

      - name: Upload to LEAP server via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SFTP_HOST_LEAP }}
          username: ${{ secrets.SFTP_USER_LEAP }}
          password: ${{ secrets.SFTP_PASS_LEAP }}
          script: |
            rm -rf /var/www/vhosts/leap.my/httpdocs/design/*
          source: "dist/design/browser/*"
          target: /var/www/vhosts/leap.my/httpdocs/design/
